# Generated by Django 5.0.2 on 2024-04-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scooter', '0001_initial'),
        ('User', '0004_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='vendor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scooter',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
