# Generated by Django 5.0.2 on 2024-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scooter', '0002_scooter_vendor_id_alter_scooter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='image',
            field=models.ImageField(default='default_scooter_image.jpg', height_field='800', upload_to='image/', width_field='600'),
        ),
    ]
