# Generated by Django 5.0.2 on 2024-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scooter', '0003_scooter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='image',
            field=models.ImageField(default='default_scooter_image.jpg', upload_to='static/images/uploads'),
        ),
    ]
